// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArNrbdhch_RBDnEmaOryUYIq5O1PwzYac',
    appId: '1:280361165039:web:3f606373b3bb27491bfb1a',
    messagingSenderId: '280361165039',
    projectId: 'login-anonymus',
    authDomain: 'login-anonymus.firebaseapp.com',
    storageBucket: 'login-anonymus.appspot.com',
    measurementId: 'G-GRS058RQ1C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZKDoV1lPyetpmu6Vb6fURoKsGxzlTQqA',
    appId: '1:280361165039:android:9d6923cb6a9538a31bfb1a',
    messagingSenderId: '280361165039',
    projectId: 'login-anonymus',
    storageBucket: 'login-anonymus.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCefxDfwN_tpaEUu5CraPFwp0zVot-i0Og',
    appId: '1:280361165039:ios:0953ee1077dcc0941bfb1a',
    messagingSenderId: '280361165039',
    projectId: 'login-anonymus',
    storageBucket: 'login-anonymus.appspot.com',
    iosBundleId: 'com.example.loginAnonymus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCefxDfwN_tpaEUu5CraPFwp0zVot-i0Og',
    appId: '1:280361165039:ios:0953ee1077dcc0941bfb1a',
    messagingSenderId: '280361165039',
    projectId: 'login-anonymus',
    storageBucket: 'login-anonymus.appspot.com',
    iosBundleId: 'com.example.loginAnonymus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArNrbdhch_RBDnEmaOryUYIq5O1PwzYac',
    appId: '1:280361165039:web:257277506903122e1bfb1a',
    messagingSenderId: '280361165039',
    projectId: 'login-anonymus',
    authDomain: 'login-anonymus.firebaseapp.com',
    storageBucket: 'login-anonymus.appspot.com',
    measurementId: 'G-7T9TDRTZP3',
  );
}
